Unfocused Development, Support for openSUSE Leap 15

diff --git a/env/ARCH b/env/ARCH
--- a/env/ARCH
+++ b/env/ARCH
@@ -15,18 +15,25 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-set -eu
+ARCH="$( arch )"
 
-list_packages() {
-    if [ "$KERNEL" = "Linux" -a "$DISTRO" = "Debian" ]; then
-        if [ "$HAS_NVIDIA_GRAPHICS" != "0" -a "$ALLOW_NONFREE" != "0" ]; then
-            echo "nvidia-driver"
-        fi
+if [ "$ARCH" = "x86_64" ]; then
+    ARCH="amd64" # Shorter than x86_64.
+elif [ "$ARCH" = "amd64" ]; then
+    : # Good.
+elif [ "$ARCH" = "OpenBSD.amd64" ]; then
+    ARCH="amd64"
+elif [ "$ARCH" = "armv6l" ]; then
+    : # Good.
+elif [ "$ARCH" = "armv7l" ]; then
+    : # Good.
+else
+    echo "env/ARCH: Unable to determine ARCH! Possible value $ARCH?" >&2
+    exit 1
+fi
 
-        if [ "$HAS_AMD_GRAPHICS" != "0" -a "$ALLOW_NONFREE" != "0" ]; then
-            echo "firmware-amd-graphics"
-        fi
-    fi
-}
+if [ "$DEBUG" != "0" ]; then
+    echo "ARCH=$ARCH"
+fi
 
-"${@}"
+export ARCH
diff --git a/env/CPU_VENDOR b/env/CPU_VENDOR
--- a/env/CPU_VENDOR
+++ b/env/CPU_VENDOR
@@ -23,7 +23,7 @@ if [ -f /proc/cpuinfo ]; then
         # My ARM systems don't have a vendor_id.
         CPU_VENDOR="arm"
     else
-        echo "Unable to determine CPU vendor!" >&2
+        echo "env/CPU_VENDOR: Unable to determine CPU vendor!" >&2
         exit 1
     fi
 elif [ -x /sbin/sysctl ]; then
@@ -31,7 +31,7 @@ elif [ -x /sbin/sysctl ]; then
     # variable names.
     CPU_VENDOR="$( /sbin/sysctl -n machdep.cpuvendor )"
 else
-    echo "Unable to determine CPU vendor!" >&2
+    echo "env/CPU_VENDOR: Unable to determine CPU vendor!" >&2
     exit 1
 fi
 
@@ -42,7 +42,7 @@ elif [ "$CPU_VENDOR" = "AuthenticAMD" ]; then
 elif [ "$CPU_VENDOR" = "arm" ]; then
     :
 else
-    echo "Unexpected CPU vendor $CPU_VENDOR!" >&2
+    echo "env/CPU_VENDOR: Unexpected CPU vendor $CPU_VENDOR!" >&2
     exit 1
 fi
 
