CPU_VENDOR
Possible CPU vendor detection for OpenBSD.

diff --git a/env/CPU_VENDOR b/env/CPU_VENDOR
--- a/env/CPU_VENDOR
+++ b/env/CPU_VENDOR
@@ -2,7 +2,15 @@
 
 set -eu
 
-CPU_VENDOR=`cat /proc/cpuinfo | grep vendor_id | grep -o ':.*' | sed 's/^: //' | uniq | head -1`
+if [ -f /proc/cpuinfo ]; then
+    CPU_VENDOR=`cat /proc/cpuinfo | grep vendor_id | grep -o ':.*' | sed 's/^: //' | uniq | head -1`
+elif [ -x /sbin/sysctl ]; then
+    CPU_VENDOR=`sysctl -n machdep.cpuvendor`
+else
+    echo "Unable to determine CPU vendor!" >&2
+    exit 1
+fi 
+
 if [ "${CPU_VENDOR}" = "GenuineIntel" ]; then
     CPU_VENDOR=intel
 elif [ "${CPU_VENDOR}" = "AuthenticAMD" ]; then
